# Generated by Django 3.1.7 on 2021-04-13 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=None)),
                ('resets', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.program')),
            ],
        ),
        migrations.CreateModel(
            name='Excersie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.workout')),
            ],
        ),
    ]
