# Generated by Django 3.1.7 on 2021-04-14 23:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0002_auto_20210414_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 23, 4, 37, 535813, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
