# Generated by Django 3.1.7 on 2021-04-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0003_auto_20210414_1904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excersise',
            new_name='Exercise',
        ),
    ]
