# Generated by Django 3.1.7 on 2021-04-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0004_auto_20210414_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='theme',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
